version: '3.7'
services:
  nginx:
    image: 'nginx:1.19.8'
    depends_on:
    - 'wordpress'
    ports:
    - '80:80'
    volumes:
    - './etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    - 'wordpress:/var/www/html'
  wordpress:
    image: 'wordpress:5.7.0-php7.4-fpm-alpine'
    restart: 'always'
    depends_on:
    - 'mysql'
    expose:
    - '9000'
    environment:
    - 'WORDPRESS_DB_HOST=mysql'
    - 'WORDPRESS_DB_USER=wordpress'
    - 'WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}'
    - 'WORDPRESS_DB_NAME=wordpress'
    volumes:
    - 'wordpress:/var/www/html'
    - './usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini:ro'
  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    expose:
    - '3306'
    environment:
    - 'MYSQL_DATABASE=wordpress'
    - 'MYSQL_USER=wordpress'
    - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    - 'MYSQL_RANDOM_ROOT_PASSWORD=1'
    volumes:
    - 'mysql:/var/lib/mysql'
volumes:
  wordpress:
  mysql:
